name: CAE_LV
channels:
  - anaconda
  - conda-forge
dependencies:
  - pip
  - numpy
  - matplotlib
  - pip:
    - tensorflow
    - Keras
    - nibabel
    - scikit-image
    - scikit-learn
    - tqdm
    - torch
    - torchio

 
